from collections import OrderedDict

dnn_input_variables = OrderedDict(
    {
        "vbf_cand_jets_pt_jet0": ["JetGoodVBF:0", "pt"],
        "vbf_cand_jets_eta_jet0": ["JetGoodVBF:0", "eta"],
        "vbf_cand_jets_phi_jet0": ["JetGoodVBF:0", "phi"],
        "vbf_cand_jets_mass_jet0": ["JetGoodVBF:0", "mass"],
        "vbf_cand_jets_pt_jet1": ["JetGoodVBF:1", "pt"],
        "vbf_cand_jets_eta_jet1": ["JetGoodVBF:1", "eta"],
        "vbf_cand_jets_phi_jet1": ["JetGoodVBF:1", "phi"],
        "vbf_cand_jets_mass_jet1": ["JetGoodVBF:1", "mass"],
        "vbf_cand_jets_pt_jet2": ["JetGoodVBF:2", "pt"],
        "vbf_cand_jets_eta_jet2": ["JetGoodVBF:2", "eta"],
        "vbf_cand_jets_phi_jet2": ["JetGoodVBF:2", "phi"],
        "vbf_cand_jets_mass_jet2": ["JetGoodVBF:2", "mass"],
        "vbf_cand_jets_pt_jet3": ["JetGoodVBF:3", "pt"],
        "vbf_cand_jets_eta_jet3": ["JetGoodVBF:3", "eta"],
        "vbf_cand_jets_phi_jet3": ["JetGoodVBF:3", "phi"],
        "vbf_cand_jets_mass_jet3": ["JetGoodVBF:3", "mass"],
        # "era": ["events", "era"],
        "HT": ["events", "HT"],
        "dijet_dEta": ["events", "dEta"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass_regr"],
        "higgs1_centrality": ["HiggsLeading", "centrality"],
        "higgs1_btagBB_wp": ["HiggsLeading", "btagBB_3wp"],
        # "higgs1_btagBB": ["HiggsLeading", "btagBB"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass_regr"],
        "higgs2_centrality": ["HiggsSubLeading", "centrality"],
        # "higgs2_btagBB_wp": ["HiggsSubLeading", "btagBB_3wp"],
        # "higgs2_btagBB": ["HiggsSubLeading", "btagBB"],
        "higgs1_DeltaR_Hj": ["HiggsLeading", "dR_Hjet_min"],
        "higgs1_mass_Hj": ["HiggsLeading", "m_Hjet_min_dR"],
        "higgs2_DeltaR_Hj": ["HiggsSubLeading", "dR_Hjet_min"],
        "higgs2_mass_Hj": ["HiggsSubLeading", "m_Hjet_min_dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "dijet_LeadingJet_pt": ["LeadingVBFJet", "pt"],
        "dijet_LeadingJet_eta": ["LeadingVBFJet", "eta"],
        "dijet_LeadingJet_phi": ["LeadingVBFJet", "phi"],
        "dijet_LeadingJet_mass": ["LeadingVBFJet", "mass"],
        "dijet_SubLeadingJet_pt": ["SubLeadingVBFJet", "pt"],
        "dijet_SubLeadingJet_eta": ["SubLeadingVBFJet", "eta"],
        "dijet_SubLeadingJet_phi": ["SubLeadingVBFJet", "phi"],
        "dijet_SubLeadingJet_mass": ["SubLeadingVBFJet", "mass"],
        "met_et": ["MET", "sumEt"],
    }
)


test_set = OrderedDict(
    {
        "vbf_cand_jets_pt_jet0": ["JetGoodVBF:0", "pt"],
        "vbf_cand_jets_eta_jet0": ["JetGoodVBF:0", "eta"],
        "vbf_cand_jets_phi_jet0": ["JetGoodVBF:0", "phi"],
        "vbf_cand_jets_mass_jet0": ["JetGoodVBF:0", "mass"],
        "vbf_cand_jets_pt_jet1": ["JetGoodVBF:1", "pt"],
        "vbf_cand_jets_eta_jet1": ["JetGoodVBF:1", "eta"],
        "vbf_cand_jets_phi_jet1": ["JetGoodVBF:1", "phi"],
        "vbf_cand_jets_mass_jet1": ["JetGoodVBF:1", "mass"],
        "vbf_cand_jets_pt_jet2": ["JetGoodVBF:2", "pt"],
        "vbf_cand_jets_eta_jet2": ["JetGoodVBF:2", "eta"],
        "vbf_cand_jets_phi_jet2": ["JetGoodVBF:2", "phi"],
        "vbf_cand_jets_mass_jet2": ["JetGoodVBF:2", "mass"],
        "vbf_cand_jets_pt_jet3": ["JetGoodVBF:3", "pt"],
        "vbf_cand_jets_eta_jet3": ["JetGoodVBF:3", "eta"],
        "vbf_cand_jets_phi_jet3": ["JetGoodVBF:3", "phi"],
        "vbf_cand_jets_mass_jet3": ["JetGoodVBF:3", "mass"],
        "era": ["events", "era"],
        "HT": ["events", "HT"],
        "dijet_dEta": ["events", "dEta"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass_regr"],
        "higgs1_centrality": ["HiggsLeading", "centrality"],
        "higgs1_btagBB_wp": ["HiggsLeading", "btagBB_3wp"],
        # "higgs1_btagBB": ["HiggsLeading", "btagBB"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass_regr"],
        "higgs2_centrality": ["HiggsSubLeading", "centrality"],
        # "higgs2_btagBB_wp": ["HiggsSubLeading", "btagBB_3wp"],
        # "higgs2_btagBB": ["HiggsSubLeading", "btagBB"],
        "higgs1_DeltaR_Hj": ["HiggsLeading", "dR_Hjet_min"],
        "higgs1_mass_Hj": ["HiggsLeading", "m_Hjet_min_dR"],
        "higgs2_DeltaR_Hj": ["HiggsSubLeading", "dR_Hjet_min"],
        "higgs2_mass_Hj": ["HiggsSubLeading", "m_Hjet_min_dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "dijet_LeadingJet_pt": ["LeadingVBFJet", "pt"],
        "dijet_LeadingJet_eta": ["LeadingVBFJet", "eta"],
        "dijet_LeadingJet_phi": ["LeadingVBFJet", "phi"],
        "dijet_LeadingJet_mass": ["LeadingVBFJet", "mass"],
        "dijet_SubLeadingJet_pt": ["SubLeadingVBFJet", "pt"],
        "dijet_SubLeadingJet_eta": ["SubLeadingVBFJet", "eta"],
        "dijet_SubLeadingJet_phi": ["SubLeadingVBFJet", "phi"],
        "dijet_SubLeadingJet_mass": ["SubLeadingVBFJet", "mass"],
        "met_et": ["MET", "sumEt"],
    }
)
