input_variables: ggf_vbf_dnn_input_variables_fw_mom_0_11

run2: False

signal_region: [hh4b_vbf_best_candidates_6_jets_nokincut_region]
background_region: [hh4b_vbf_best_candidates_6_jets_nokincut_region]

signal_sample:
  [
    VBFHHto4B_CV-1p74_C2V-1p37_C3-14p4,
    VBFHHto4B_CV-m0p012_C2V-0p030_C3-10p2,
    VBFHHto4B_CV-m0p758_C2V-1p44_C3-m19p3,
    VBFHHto4B_CV-m0p962_C2V-0p959_C3-m1p43,
    VBFHHto4B_CV-m1p21_C2V-1p94_C3-m0p94,
    VBFHHto4B_CV-m1p60_C2V-2p72_C3-m1p36,
    VBFHHto4B_CV-m1p83_C2V-3p57_C3-m3p39,
    VBFHHto4B_CV-m2p12_C2V-3p87_C3-m5p96,
    VBFHHto4B_CV_1_C2V_0_C3_1,
    VBFHHto4B_CV_1_C2V_1_C3_1,
  ]
background_sample:
  [
    GluGlutoHHto4B_spanet_kl-1p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-m2p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-m1p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-5p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-2p45_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-0p00_kt-0p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-3p50_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-4p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-3p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-2p00_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-1p50_kt-1p00_c2-0p00_skimmed,
    GluGlutoHHto4B_spanet_kl-0p50_kt-1p00_c2-0p00_skimmed,
  ]
signal_dataset:
  [
    VBFHHto4B_CV-1p74_C2V-1p37_C3-14p4__2022_postEE,
    VBFHHto4B_CV-m0p012_C2V-0p030_C3-10p2__2022_postEE,
    VBFHHto4B_CV-m0p758_C2V-1p44_C3-m19p3__2022_postEE,
    VBFHHto4B_CV-m0p962_C2V-0p959_C3-m1p43__2022_postEE,
    VBFHHto4B_CV-m1p21_C2V-1p94_C3-m0p94__2022_postEE,
    VBFHHto4B_CV-m1p60_C2V-2p72_C3-m1p36__2022_postEE,
    VBFHHto4B_CV-m1p83_C2V-3p57_C3-m3p39__2022_postEE,
    VBFHHto4B_CV-m2p12_C2V-3p87_C3-m5p96__2022_postEE,
    VBFHHto4B_CV_1_C2V_0_C3_1__2022_postEE,
    VBFHHto4B_CV_1_C2V_1_C3_1__2022_postEE,
  ]
background_dataset:
  [
    GluGlutoHHto4B_spanet_kl-1p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-m2p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-m1p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-5p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-2p45_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-0p00_kt-0p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-3p50_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-4p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-3p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-2p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-1p50_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-0p50_kt-1p00_c2-0p00_2022_postEE,
  ]

# split_oversample: True

ML_model: DNN_softmax_reweight_model

data_format: parquet

batch_size: 512
epochs: 50

learning_rate: 1e-3
learning_rate_schedule: e5_drop75

early_stopping: True
patience: 5
min_delta: 1e-5

eval_param: loss

train_fraction: 0.7125
val_fraction: 0.2375
test_fraction: 0.05

data_dirs:
  [
    /work/mmalucch/out_hh4b/VBF/out_ggf_vbf_spanet_input_AllKlambda_DetaMjjCentrality_VBFPairingAfterHiggsPairing_DNNVars_FW_momenta_vbf_regions/,
  ]
